/** Protected application routes */
export const PATH_HOME = '/';
export const PATH_TEAMS = '/teams';
export const PATH_TODOS = '/todos';
export const PATH_AGENDA = '/agenda';
export const PATH_PROFILE = '/profile';
export const PATH_SETTINGS = '/settings';
export const PATH_LOGIN = '/login';
export const PATH_REGISTER = '/register';
